name: Pipeline Framework 4.7.2

on:
  workflow_call:
    inputs:
      solution:
        description: 'Path to the solution file'
        required: true
        type: string
      buildConfiguration:
        description: 'Build configuration (e.g., Release or Debug)'
        required: false
        default: 'Release'
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # - name: Setup NuGet
      #   uses: NuGet/setup-nuget@v1

      # - name: Restore NuGet packages
      #   run: nuget restore ${{ inputs.solution }}

      # - name: Build solution
      #   run: msbuild ${{ inputs.solution }} /p:Configuration=${{ inputs.buildConfiguration }}

      # - name: Run tests
      #   run: |
      #     vstest.console.exe **\*Test*.dll
      #   env:
      #     VSTEST_ADDITIONAL_ARGS: '--logger:trx'